name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 2 * * *"   # runs daily at 02:00 UTC
  workflow_dispatch:        # lets you trigger it manually too

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: .github/profile-3d-setting.json

      - name: Commit & Push
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add -A .
          git commit -m "update 3d contribution graph" || exit 0
          git push